# Generated by Django 4.0.4 on 2022-05-27 20:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meetingName', models.CharField(max_length=13, unique=True)),
                ('meetingPswd', models.CharField(max_length=100)),
                ('meetingToken', models.CharField(max_length=12, null=True, unique=True)),
                ('tokenValidUntil', models.DateTimeField(blank=True, null=True)),
                ('newTokenDate', models.DateTimeField(blank=True, null=True)),
                ('meetingAdmin', models.CharField(max_length=50, unique=True)),
                ('isHost', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meetingName', models.CharField(max_length=13)),
                ('participantId', models.CharField(max_length=50)),
                ('accessTime', models.DateTimeField(default=datetime.datetime(2022, 5, 27, 20, 59, 20, 488804))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pswd', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=31)),
                ('emailToken', models.CharField(blank=True, max_length=12, unique=True)),
                ('emailVerified', models.BooleanField(default=False)),
                ('loginTries', models.IntegerField(default=0)),
                ('penaltyExpirationDate', models.DateTimeField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
    ]
